version: '3.8'

services:

  jaeger:
    image: jaegertracing/all-in-one:1.41
    container_name: jaeger
    environment:
      - COLLECTOR_OTLP_ENABLED=true   
    ports:
      - "5775:5775"    # UDP port for sampling
      - "6831:6831"    # UDP port for tracing
      - "6832:6832"    # UDP port for tracing
      - "5778:5778"    # HTTP port for Jaeger UI
      - "16686:16686"  # HTTP port for Jaeger UI
      - "14250:14250"  # gRPC port
      - "14268:14268"  # HTTP port for traces submission
      - "14250:14250"  # gRPC port for traces submission
      - "4317:4317"    # gRPC port for OpenTelemetry protocol
      - "4318:4318"    # HTTP port for OpenTelemetry protocol

  mysql:
    image: mysql:latest
    container_name: my-mysql-container
    environment:
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "3306:3306"
    volumes:
      - my-mysql-volume:/var/lib/mysql
    restart: always

volumes:
  my-mysql-volume: